name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - run: npm run build
      - name: Copy dist to another repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'krzysztofkrolikowski'
          destination-repository-name: 'krzysztofkrolikowski.github.io'
          user-email: 'example@email.com'
          target-branch: 'main'

#uses: dmnemec/copy_file_to_another_repo_action@main
#  env:
#    API_TOKEN_GITHUB: ${{ secrets.API_KEY_GITHUB }}
#  with:
#    source_file: 'dist/assets'
#    destination_repo: 'krzysztofkrolikowski/krzysztofkrolikowski.github.io'
#    user_email: 'example@email.com'
#    user_name: 'example'
#    commit_message: 'Deploy'
